name: 打包Python为APK

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装依赖环境
        run:
          sudo apt update -y
          sudo apt install -y openjdk-17-jdk python3-pip git
          pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          pip install cython
          pip install buildozer

      - name: 构建APK安装包
        run: buildozer android debug

      - name: 上传APK产物
        uses: actions/upload-artifact@v4
        with:
          name: Python-APK
          path: bin/*.apk
